// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiHome4.Data;

#nullable disable

namespace WebApiHome4.Migrations
{
    [DbContext(typeof(BookCatalogDbContext))]
    [Migration("20261002163528_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.31");

            modelBuilder.Entity("WebApiHome4.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Джон Толкин",
                            Description = "Повесть о путешествии Бильбо Бэггинса.",
                            Price = 4500m,
                            Title = "Хоббит",
                            Year = 1937
                        },
                        new
                        {
                            Id = 2,
                            Author = "Джордж Оруэлл",
                            Description = "Антиутопический роман о тоталитарном обществе.",
                            Price = 3900m,
                            Title = "1984",
                            Year = 1949
                        },
                        new
                        {
                            Id = 3,
                            Author = "Джордж Оруэлл",
                            Description = "Аллегорическая повесть-притча.",
                            Price = 3200m,
                            Title = "Скотный двор",
                            Year = 1945
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
